from __future__ import annotations

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)
from starlette.requests import Request
from starlette.responses import Response

REGISTRY = CollectorRegistry()

HTTP_REQUESTS_TOTAL = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "path", "status"],
    registry=REGISTRY,
)
HTTP_REQUEST_DURATION = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency",
    ["method", "path"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
    registry=REGISTRY,
)
HTTP_REQUESTS_INFLIGHT = Gauge(
    "http_requests_inflight",
    "In-flight HTTP requests",
    ["method"],
    registry=REGISTRY,
)
LLM_REQUESTS_TOTAL = Counter(
    "llm_requests_total",
    "Total LLM requests",
    ["provider", "model"],
    registry=REGISTRY,
)
LLM_REQUEST_DURATION = Histogram(
    "llm_request_duration_seconds",
    "LLM call latency",
    ["provider"],
    registry=REGISTRY,
)
LLM_TOKENS_TOTAL = Counter(
    "llm_tokens_total",
    "Total tokens generated by the LLM",
    ["provider", "direction"],
    registry=REGISTRY,
)
RETRIEVAL_REQUESTS_TOTAL = Counter(
    "retrieval_requests_total",
    "Total retrieval queries",
    ["backend"],
    registry=REGISTRY,
)
INGESTED_DOCUMENTS_TOTAL = Counter(
    "ingested_documents_total",
    "Total documents ingested",
    registry=REGISTRY,
)
QDRANT_COLLECTION_POINTS = Gauge(
    "qdrant_collection_points",
    "Points in the Qdrant collection",
    ["collection"],
    registry=REGISTRY,
)
DATABASE_POOL_SIZE = Gauge(
    "database_pool_size",
    "Database connection pool size",
    registry=REGISTRY,
)


def observe_llm(provider: str, model: str, duration: float, tokens: int) -> None:
    LLM_REQUESTS_TOTAL.labels(provider=provider, model=model).inc()
    LLM_REQUEST_DURATION.labels(provider=provider).observe(duration)
    if tokens:
        LLM_TOKENS_TOTAL.labels(provider=provider, direction="output").inc(tokens)


def metrics_response(request: Request) -> Response:
    from fastapi.responses import Response as FastAPIResponse

    body = generate_latest(REGISTRY)
    return FastAPIResponse(content=body, media_type=CONTENT_TYPE_LATEST)
